version: '3.3'

# envs https://medium.com/softonic-eng/docker-compose-from-development-to-production-88000124a57c

services:

#  keycloak:
#    image: quay.io/keycloak/keycloak:11.0.3
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#    ports:
#    - 8081:8080

  mysql:
    image: mysql:8
    container_name: database
    restart: always
    environment:
      - MYSQL_DATABASE=${databaseName}
      - MYSQL_USER=${sqlUser}
      - MYSQL_PASSWORD=${sqlPassword}
      - MYSQL_ROOT_PASSWORD=${sqlRootPassword}
    expose:
      - 3306
    ports:
    - 3306:3306
    networks:
      - sql_net

  #  nitter:
  #    image: zedeus/nitter:latest
  #    volumes:
  #      - ./modules/nitter/nitter.conf:/src/nitter.conf
  #    ports:
  #      - 8000:8080

  # https://hub.docker.com/_/neo4j/
  neo4j:
    image: neo4j
    restart: always
    container_name: neo01
    environment:
      - NEO4J_AUTH=none
    expose:
      - 7474
      - 7687
    networks:
      - neo4j_net

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    expose:
      - 9200
    networks:
      - es_net

  rich-app:
    image: rich-rss:app
    restart: always
    ports:
      - 8000:80
    networks:
      - frontend_net

  rich-node:
    image: damoeb/rich-rss:rss-node
    restart: always
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://${sqlUser}:${sqlPassword}@database:3306/${databaseName}
    ports:
      - 8001:3000
    expose:
      - 3000
    networks:
      - frontend_net
      - backend_net
      - sql_net

  rich-kotlin:
    image: damoeb/rich-rss:rss-kotlin
    restart: always
    depends_on:
      - mysql
      - rich-node
    expose:
      - 8080
    environment:
      - sqlUser=${sqlUser}
      - sqlPassword=${sqlPassword}
      - DATABASE_URL=jdbc:mysql://database:3306/${databaseName}
    networks:
      - backend_net
      - sql_net

  rich-graph:
    image: damoeb/rich-rss:graph
    restart: always
    depends_on:
      - mysql
      - es
      - neo4j
    expose:
      - 8080
    networks:
      - backend_net
      - neo4j_net
      - es_net
      - sql_net

volumes:
  esdata01:
    driver: local

networks:
  es_net:
    driver: bridge
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge
  neo4j_net:
    driver: bridge
  sql_net:
    driver: bridge
