version: '3.3'

# envs https://medium.com/softonic-eng/docker-compose-from-development-to-production-88000124a57c

services:

#  keycloak:
#    image: quay.io/keycloak/keycloak:11.0.3
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#    ports:
#    - 8081:8080

# todo mag use postgres, not mysql
  #  postgres:
  #    image: library/postgres:13-alpine
  #    environment:
  #      - POSTGRES_DB=rich-rss
  #      - POSTGRES_USER=admin
  #      - POSTGRES_PASSWORD=admin
  #    ports:
  #    - 5434:5432

  #  rss-proxy:
  #    image: damoeb/rss-proxy
  #    ports:
  #      - 3000:3000

  #  see https://github:com/buildkite/docker-puppeteer/tree/master/example
  #  puppeteer:
  #    image: buildkite/puppeteer
  #    ports:
  #      - 3001:8080

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=rich-rss
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
