version: '3.3'

# envs https://medium.com/softonic-eng/docker-compose-from-development-to-production-88000124a57c

services:

#  keycloak:
#    image: quay.io/keycloak/keycloak:11.0.3
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#    ports:
#    - 8081:8080

# todo mag use postgres, not mysql
  #  postgres:
  #    image: library/postgres:13-alpine
  #    environment:
  #      - POSTGRES_DB=rich-rss
  #      - POSTGRES_USER=admin
  #      - POSTGRES_PASSWORD=admin
  #    ports:
  #    - 5434:5432

  #  rss-proxy:
  #    image: damoeb/rss-proxy
  #    ports:
  #      - 3000:3000

  #  see https://github:com/buildkite/docker-puppeteer/tree/master/example
  #  puppeteer:
  #    image: buildkite/puppeteer
  #    ports:
  #      - 3001:8080

#  zookeeper:
#    image: zookeeper:3.4.9
#    hostname: zoo
#    ports:
#      - "2181:2181"
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_PORT: 2181
#      ZOO_SERVERS: server.1=zoo1:2888:3888
#    volumes:
#      - ./zk-single-kafka-single/zoo1/data:/data
#      - ./zk-single-kafka-single/zoo1/datalog:/datalog
#
#  kafka:
#    image: confluentinc/cp-kafka:5.5.1
#    hostname: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
#      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
#      KAFKA_BROKER_ID: 1
#      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    volumes:
#      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
#    depends_on:
#      - zookeeper

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=rich-rss
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306

  rssproxy:
    image: damoeb/rss-proxy
    ports:
      - 3001:3000

  nitter:
    image: zedeus/nitter:latest
    volumes:
      - ./modules/nitter/nitter.conf:/src/nitter.conf
    ports:
      - 8000:8080
