version: '3.4'

# envs https://medium.com/softonic-eng/docker-compose-from-development-to-production-88000124a57c

services:

#  neo4j:
#    image: neo4j
#    ports:
#      - "7474:7474"
#      - "7687:7687"
#    volumes:
#      - ./conf:/conf
#      - ./data:/data
#      - ./import:/import
#      - ./logs:/logs
#      - ./plugins:/plugins
#    environment:
      # Raise memory limits
#      - NEO4J_dbms_memory_pagecache_size=1G
#      - NEO4J_dbms.memory.heap.initial_size=1G
#      - NEO4J_dbms_memory_heap_max__size=1G

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_setting_jvm_heap_size
#  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
#    container_name: es
#    environment:
#      #- ES_JAVA_OPTS="-Xms1g -Xmx1g"
#      - discovery.type=single-node
##      - node.name=es-node
##      - cluster.name=es-cluster
##      - discovery.type=single-node
#    ports:
#      - "9200:9200"

  smtp:
    image: jijiechen/papercut:latest
    ports:
      - "25:25"
      - "37408:37408"

  nitter:
    container_name: nitter
    image: zedeus/nitter:latest
    ports:
      - "8081:8080"
    volumes:
      - ./docker/nitter.conf:/src/nitter.conf:ro
    depends_on:
      - nitter-redis
    restart: unless-stopped
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
      interval: 30s
      timeout: 5s
      retries: 2

  nitter-redis:
    image: redis:6-alpine
    container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
#    volumes:
#      - nitter-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2

  # https://hub.docker.com/_/postgres/
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
#      - POSTGRES_DB=${databaseName}
      - POSTGRES_DB=rich-rss
#      - POSTGRES_USER=${sqlUser}
      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=${databasePassword}
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
    ports:
    - "5432:5432"
    networks:
      - postgres

#  rich-agent:
#    image: damoeb/rich-rss:agent-0
#    security_opt:
#      - seccomp=./chrome.json
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
##    healthcheck:
##      test: curl -f https://localhost:3000 || exit 1
#    networks:
#      - puppeteer
#      - monitoring

#  rich-core:
#    image: damoeb/rich-rss:core
#    restart: unless-stopped
##    healthcheck:
##      test: curl -f https://localhost:8080 || exit 1
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    environment:
#      - sqlUser=${sqlUser}
#      - sqlPassword=${sqlPassword}
#      - DATABASE_URL=jdbc:postgresql://postgres:5432/${databaseName}
#      - nitterHost=nitter
#      - invidiousHost=invidious
#      - APP_PUBLIC_URL=http://localhost:8080
#      - spring_profiles_active=sso,database,monitoring
#      - APP_TIMEZONE=Europe/Berlin
#      - LOG_LEVEL=info
#      - APP_JWT_SECRET=60ae393744191ee58869f700c1d27647b0b64d42
#      - APP_ACTUATOR_PASSWORD=password
#    networks:
#      - postgres
#      - monitoring
#      - puppeteer

# ----------------------------------------------------------------------------------------------------------------------
# -- MONITORING
# ----------------------------------------------------------------------------------------------------------------------

  loki:
    image: grafana/loki:2.5.0
    volumes:
      - ./docker/loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  autoheal:
    image: willfarrell/autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring

secrets:
  TOKEN_SECRET:
    file: ./tokenSecret.txt

networks:
  postgres:
    driver: bridge
  monitoring:
    driver: bridge
  puppeteer:
    driver: bridge
